<a href="https://www.kaggle.com/code/raghav0079/hull-tactical?scriptVersionId=288658059" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/hull-tactical-market-prediction/train.csv
/kaggle/input/hull-tactical-market-prediction/test.csv
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/default_inference_server.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/default_gateway.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/__init__.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/templates.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/base_gateway.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/relay.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/kaggle_evaluation.proto
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/__init__.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/generated/kaggle_evaluation_pb2.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/generated/kaggle_evaluation_pb2_grpc.py
/kaggle/input/hull-tactical-market-prediction/kaggle_evaluation/core/generated/__init__.py

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [3]:
import os
import pandas as pd

# 1. Create a list to store the file paths
file_list = []

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        # Construct the full path and add to list
        full_path = os.path.join(dirname, filename)
        file_list.append(full_path)

# 2. Create the DataFrame
df = pd.DataFrame(file_list, columns=['file_path'])

# Display the first few rows
print(df.head())

                                           file_path
0  /kaggle/input/hull-tactical-market-prediction/...
1  /kaggle/input/hull-tactical-market-prediction/...
2  /kaggle/input/hull-tactical-market-prediction/...
3  /kaggle/input/hull-tactical-market-prediction/...
4  /kaggle/input/hull-tactical-market-prediction/...

In [4]:
import pandas as pd
import os

for path in df['file_path'].head(10): # Checking more files now
    # Skip non-csv files
    if not path.endswith('.csv'):
        continue
        
    try:
        # We use low_memory=False to handle mixed data types 
        # and nrows=5 to load it quickly
        temp_df = pd.read_csv(path, nrows=5, low_memory=False)
        
        print(f"\n{'='*20}")
        print(f"FILE: {os.path.basename(path)}")
        print(f"{'='*20}")
        display(temp_df.head(3))
        
    except Exception as e:
        print(f"Skipping {os.path.basename(path)}: Could not read (Error: {e})")

====================
FILE: train.csv
====================

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,forward_returns,risk_free_rate,market_forward_excess_returns
0,0,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002421,0.000301,-0.003038
1,1,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008495,0.000303,-0.009114
2,2,0,0,0,1,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.009624,0.000301,-0.010243

====================
FILE: test.csv
====================

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V4,V5,V6,V7,V8,V9,is_scored,lagged_forward_returns,lagged_risk_free_rate,lagged_market_forward_excess_returns
0,8980,0,0,0,0,1,0,0,1,0,...,0.828042,0.999173,0.759921,-0.803127,0.170966,-0.751909,True,0.003541,0.000161,0.003068
1,8981,0,0,0,0,1,0,0,1,0,...,0.831349,1.120336,0.556217,-0.686192,0.141865,-0.660326,True,-0.005964,0.000162,-0.006437
2,8982,0,0,0,0,1,0,0,0,1,...,0.832672,1.088992,0.665344,-0.459367,0.199405,-0.510979,True,-0.007410,0.000160,-0.007882

In [5]:


# Load the data (using low_memory=False due to the mixed types/large values we saw earlier)
df_a = pd.read_csv('/kaggle/input/hull-tactical-market-prediction/train.csv', low_memory=False)
df_b = pd.read_csv('/kaggle/input/hull-tactical-market-prediction/test.csv', low_memory=False)

# List of dataframes to summarize
datasets = {"TRAIN DATA": df_a, "TEST DATA": df_b}

for name, data in datasets.items():
    print(f"\n{'='*30}")
    print(f" STATS FOR {name} ")
    print(f"{'='*30}")
    
    print("\n--- INFO (Data Types & Nulls) ---")
    print(data.info(verbose=True, show_counts=True)) # verbose=True ensures all 98 columns are listed
    
    print("\n--- DESCRIBE (Statistical Summary) ---")
    display(data.describe())
    
    print("\n--- MISSING VALUES (Top 10) ---")
    print(data.isnull().sum().sort_values(ascending=False).head(10))

==============================
 STATS FOR TRAIN DATA
==============================

--- INFO (Data Types & Nulls) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9048 entries, 0 to 9047
Data columns (total 98 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date_id                        9048 non-null   int64
 1   D1                             9048 non-null   int64
 2   D2                             9048 non-null   int64
 3   D3                             9048 non-null   int64
 4   D4                             9048 non-null   int64
 5   D5                             9048 non-null   int64
 6   D6                             9048 non-null   int64
 7   D7                             9048 non-null   int64
 8   D8                             9048 non-null   int64
 9   D9                             9048 non-null   int64
 10  E1                             7264 non-null   float64
 11  E10                            8042 non-null   float64
 12  E11                            8042 non-null   float64
 13  E12                            8042 non-null   float64
 14  E13                            8042 non-null   float64
 15  E14                            8042 non-null   float64
 16  E15                            8042 non-null   float64
 17  E16                            8042 non-null   float64
 18  E17                            8042 non-null   float64
 19  E18                            8042 non-null   float64
 20  E19                            8042 non-null   float64
 21  E2                             8042 non-null   float64
 22  E20                            7432 non-null   float64
 23  E3                             8042 non-null   float64
 24  E4                             8042 non-null   float64
 25  E5                             8042 non-null   float64
 26  E6                             8042 non-null   float64
 27  E7                             2079 non-null   float64
 28  E8                             8042 non-null   float64
 29  E9                             8042 non-null   float64
 30  I1                             8042 non-null   float64
 31  I2                             8042 non-null   float64
 32  I3                             8042 non-null   float64
 33  I4                             8042 non-null   float64
 34  I5                             8042 non-null   float64
 35  I6                             8042 non-null   float64
 36  I7                             8042 non-null   float64
 37  I8                             8042 non-null   float64
 38  I9                             8042 non-null   float64
 39  M1                             3501 non-null   float64
 40  M10                            8042 non-null   float64
 41  M11                            8042 non-null   float64
 42  M12                            8042 non-null   float64
 43  M13                            3508 non-null   float64
 44  M14                            3508 non-null   float64
 45  M15                            8042 non-null   float64
 46  M16                            8042 non-null   float64
 47  M17                            8042 non-null   float64
 48  M18                            8042 non-null   float64
 49  M2                             5831 non-null   float64
 50  M3                             7030 non-null   float64
 51  M4                             8042 non-null   float64
 52  M5                             5765 non-null   float64
 53  M6                             4005 non-null   float64
 54  M7                             8042 non-null   float64
 55  M8                             8042 non-null   float64
 56  M9                             8042 non-null   float64
 57  P1                             8042 non-null   float64
 58  P10                            8042 non-null   float64
 59  P11                            8042 non-null   float64
 60  P12                            8042 non-null   float64
 61  P13                            8042 non-null   float64
 62  P2                             8042 non-null   float64
 63  P3                             8042 non-null   float64
 64  P4                             8042 non-null   float64
 65  P5                             7474 non-null   float64
 66  P6                             7410 non-null   float64
 67  P7                             7432 non-null   float64
 68  P8                             8042 non-null   float64
 69  P9                             8042 non-null   float64
 70  S1                             8042 non-null   float64
 71  S10                            8042 non-null   float64
 72  S11                            8042 non-null   float64
 73  S12                            5511 non-null   float64
 74  S2                             8042 non-null   float64
 75  S3                             3315 non-null   float64
 76  S4                             8042 non-null   float64
 77  S5                             7537 non-null   float64
 78  S6                             8042 non-null   float64
 79  S7                             8042 non-null   float64
 80  S8                             6039 non-null   float64
 81  S9                             8042 non-null   float64
 82  V1                             8042 non-null   float64
 83  V10                            2999 non-null   float64
 84  V11                            8042 non-null   float64
 85  V12                            8042 non-null   float64
 86  V13                            7537 non-null   float64
 87  V2                             8042 non-null   float64
 88  V3                             8042 non-null   float64
 89  V4                             8042 non-null   float64
 90  V5                             7536 non-null   float64
 91  V6                             8042 non-null   float64
 92  V7                             7537 non-null   float64
 93  V8                             8042 non-null   float64
 94  V9                             4509 non-null   float64
 95  forward_returns                9048 non-null   float64
 96  risk_free_rate                 9048 non-null   float64
 97  market_forward_excess_returns  9048 non-null   float64
dtypes: float64(88), int64(10)
memory usage: 6.8 MB
None

--- DESCRIBE (Statistical Summary) ---

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,forward_returns,risk_free_rate,market_forward_excess_returns
count,9048.000000,9048.000000,9048.000000,9048.000000,9048.000000,9048.000000,9048.000000,9048.000000,9048.000000,9048.000000,...,8042.000000,8042.000000,7536.000000,8042.000000,7537.000000,8042.000000,4509.000000,9048.000000,9048.000000,9048.000000
mean,4523.500000,0.031609,0.031609,0.047856,0.575265,0.190760,-0.238174,0.045756,0.142905,0.143236,...,0.487920,0.505426,0.373707,0.290294,0.144482,0.302430,0.122810,0.000470,0.000107,0.000052
std,2612.076951,0.174967,0.174967,0.213473,0.494330,0.392922,0.425990,0.208967,0.349995,0.350333,...,0.306253,0.306571,1.149195,0.313430,1.322779,0.350292,1.270592,0.010535,0.000088,0.010552
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000661,0.000661,-2.723527,0.000661,-2.027551,0.000661,-1.497420,-0.039754,-0.000004,-0.040582
25%,2261.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.205688,0.234954,-0.466911,0.000661,-0.794254,0.000661,-0.731204,-0.004321,0.000008,-0.004751
50%,4523.500000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.488757,0.516865,0.283280,0.185185,-0.103035,0.098049,-0.181941,0.000661,0.000099,0.000257
75%,6785.250000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.759094,0.770503,1.117657,0.525132,0.788774,0.587302,0.670649,0.005891,0.000193,0.005469
max,9047.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,6.809912,1.000000,12.678264,1.000000,12.997540,0.040661,0.000317,0.040551

--- MISSING VALUES (Top 10) ---
E7     6969
V10    6049
S3     5733
M1     5547
M13    5540
M14    5540
M6     5043
V9     4539
S12    3537
M5     3283
dtype: int64

==============================
 STATS FOR TEST DATA
==============================

--- INFO (Data Types & Nulls) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 99 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   date_id                               10 non-null     int64
 1   D1                                    10 non-null     int64
 2   D2                                    10 non-null     int64
 3   D3                                    10 non-null     int64
 4   D4                                    10 non-null     int64
 5   D5                                    10 non-null     int64
 6   D6                                    10 non-null     int64
 7   D7                                    10 non-null     int64
 8   D8                                    10 non-null     int64
 9   D9                                    10 non-null     int64
 10  E1                                    10 non-null     float64
 11  E10                                   10 non-null     float64
 12  E11                                   10 non-null     float64
 13  E12                                   10 non-null     float64
 14  E13                                   10 non-null     float64
 15  E14                                   10 non-null     float64
 16  E15                                   10 non-null     float64
 17  E16                                   10 non-null     float64
 18  E17                                   10 non-null     float64
 19  E18                                   10 non-null     float64
 20  E19                                   10 non-null     float64
 21  E2                                    10 non-null     float64
 22  E20                                   10 non-null     float64
 23  E3                                    10 non-null     float64
 24  E4                                    10 non-null     float64
 25  E5                                    10 non-null     float64
 26  E6                                    10 non-null     float64
 27  E7                                    10 non-null     float64
 28  E8                                    10 non-null     float64
 29  E9                                    10 non-null     float64
 30  I1                                    10 non-null     float64
 31  I2                                    10 non-null     float64
 32  I3                                    10 non-null     float64
 33  I4                                    10 non-null     float64
 34  I5                                    10 non-null     float64
 35  I6                                    10 non-null     float64
 36  I7                                    10 non-null     float64
 37  I8                                    10 non-null     float64
 38  I9                                    10 non-null     float64
 39  M1                                    10 non-null     float64
 40  M10                                   10 non-null     float64
 41  M11                                   10 non-null     float64
 42  M12                                   10 non-null     float64
 43  M13                                   10 non-null     float64
 44  M14                                   10 non-null     float64
 45  M15                                   10 non-null     float64
 46  M16                                   10 non-null     float64
 47  M17                                   10 non-null     float64
 48  M18                                   10 non-null     float64
 49  M2                                    10 non-null     float64
 50  M3                                    10 non-null     float64
 51  M4                                    10 non-null     float64
 52  M5                                    10 non-null     float64
 53  M6                                    10 non-null     float64
 54  M7                                    10 non-null     float64
 55  M8                                    10 non-null     float64
 56  M9                                    10 non-null     float64
 57  P1                                    10 non-null     float64
 58  P10                                   10 non-null     float64
 59  P11                                   10 non-null     float64
 60  P12                                   10 non-null     float64
 61  P13                                   10 non-null     float64
 62  P2                                    10 non-null     float64
 63  P3                                    10 non-null     float64
 64  P4                                    10 non-null     float64
 65  P5                                    10 non-null     float64
 66  P6                                    10 non-null     float64
 67  P7                                    10 non-null     float64
 68  P8                                    10 non-null     float64
 69  P9                                    10 non-null     float64
 70  S1                                    10 non-null     float64
 71  S10                                   10 non-null     float64
 72  S11                                   10 non-null     float64
 73  S12                                   10 non-null     float64
 74  S2                                    10 non-null     float64
 75  S3                                    10 non-null     float64
 76  S4                                    10 non-null     float64
 77  S5                                    10 non-null     float64
 78  S6                                    10 non-null     float64
 79  S7                                    10 non-null     float64
 80  S8                                    10 non-null     float64
 81  S9                                    10 non-null     float64
 82  V1                                    10 non-null     float64
 83  V10                                   10 non-null     float64
 84  V11                                   10 non-null     float64
 85  V12                                   10 non-null     float64
 86  V13                                   10 non-null     float64
 87  V2                                    10 non-null     float64
 88  V3                                    10 non-null     float64
 89  V4                                    10 non-null     float64
 90  V5                                    10 non-null     float64
 91  V6                                    10 non-null     float64
 92  V7                                    10 non-null     float64
 93  V8                                    10 non-null     float64
 94  V9                                    10 non-null     float64
 95  is_scored                             10 non-null     bool
 96  lagged_forward_returns                10 non-null     float64
 97  lagged_risk_free_rate                 10 non-null     float64
 98  lagged_market_forward_excess_returns  10 non-null     float64
dtypes: bool(1), float64(88), int64(10)
memory usage: 7.8 KB
None

--- DESCRIBE (Statistical Summary) ---

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,lagged_forward_returns,lagged_risk_free_rate,lagged_market_forward_excess_returns
count,10.00000,10.0,10.0,10.000000,10.0,10.000000,10.0,10.000000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,8984.50000,0.0,0.0,0.100000,0.0,0.400000,0.0,0.100000,0.200000,0.300000,...,0.573743,0.819907,1.010369,0.747487,-0.679972,0.145238,-0.649404,0.001702,0.000158,0.001232
std,3.02765,0.0,0.0,0.316228,0.0,0.516398,0.0,0.316228,0.421637,0.483046,...,0.223494,0.024329,0.131349,0.111075,0.099564,0.038423,0.065991,0.005482,0.000002,0.005483
min,8980.00000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.066799,0.783730,0.785877,0.556217,-0.803127,0.079034,-0.751909,-0.007410,0.000155,-0.007882
25%,8982.25000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.472553,0.797784,0.956951,0.677910,-0.721884,0.126984,-0.670282,-0.001594,0.000156,-0.002063
50%,8984.50000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0.651455,0.832011,1.020080,0.782738,-0.700005,0.142361,-0.657186,0.002674,0.000159,0.002207
75%,8986.75000,0.0,0.0,0.000000,0.0,1.000000,0.0,0.000000,0.000000,0.750000,...,0.692295,0.837467,1.083753,0.823247,-0.685251,0.168651,-0.647103,0.004950,0.000160,0.004479
max,8989.00000,0.0,0.0,1.000000,0.0,1.000000,0.0,1.000000,1.000000,1.000000,...,0.892196,0.839947,1.226772,0.879630,-0.459367,0.199405,-0.510979,0.008357,0.000162,0.007887

--- MISSING VALUES (Top 10) ---
date_id    0
D1         0
D2         0
D3         0
D4         0
D5         0
D6         0
D7         0
D8         0
D9         0
dtype: int64

# Exploratory Data Analysis (EDA)

## Overview
This section provides a comprehensive analysis of the Hull Tactical dataset to understand:
- Data structure and quality
- Feature distributions and relationships
- Missing values and outliers
- Target variable characteristics

In [6]:
# Dataset shapes and basic info
print("="*50)
print("DATASET OVERVIEW")
print("="*50)
print(f"Training set shape: {df_a.shape}")
print(f"Test set shape: {df_b.shape}")
print(f"\nTraining set columns: {list(df_a.columns)}")
print(f"Test set columns: {list(df_b.columns)}")
print(f"\nColumns in train but not in test: {set(df_a.columns) - set(df_b.columns)}")
print(f"Columns in test but not in train: {set(df_b.columns) - set(df_a.columns)}")

==================================================
DATASET OVERVIEW
==================================================
Training set shape: (9048, 98)
Test set shape: (10, 99)

Training set columns: ['date_id', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'E1', 'E10', 'E11', 'E12', 'E13', 'E14', 'E15', 'E16', 'E17', 'E18', 'E19', 'E2', 'E20', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8', 'E9', 'I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I8', 'I9', 'M1', 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16', 'M17', 'M18', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'P1', 'P10', 'P11', 'P12', 'P13', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'S1', 'S10', 'S11', 'S12', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'V1', 'V10', 'V11', 'V12', 'V13', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'forward_returns', 'risk_free_rate', 'market_forward_excess_returns']
Test set columns: ['date_id', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'E1', 'E10', 'E11', 'E12', 'E13', 'E14', 'E15', 'E16', 'E17', 'E18', 'E19', 'E2', 'E20', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8', 'E9', 'I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I8', 'I9', 'M1', 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16', 'M17', 'M18', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'P1', 'P10', 'P11', 'P12', 'P13', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'S1', 'S10', 'S11', 'S12', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'V1', 'V10', 'V11', 'V12', 'V13', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'is_scored', 'lagged_forward_returns', 'lagged_risk_free_rate', 'lagged_market_forward_excess_returns']

Columns in train but not in test: {'market_forward_excess_returns', 'risk_free_rate', 'forward_returns'}
Columns in test but not in train: {'lagged_forward_returns', 'is_scored', 'lagged_risk_free_rate', 'lagged_market_forward_excess_returns'}

In [7]:
# Missing values analysis for training set
print("="*50)
print("MISSING VALUES - TRAINING SET")
print("="*50)
missing_train = df_a.isnull().sum()
missing_train_pct = (df_a.isnull().sum() / len(df_a)) * 100

missing_df_train = pd.DataFrame({
    'Column': missing_train.index,
    'Missing Count': missing_train.values,
    'Missing Percentage': missing_train_pct.values
})

missing_df_train = missing_df_train[missing_df_train['Missing Count'] > 0].sort_values('Missing Count', ascending=False)

if len(missing_df_train) > 0:
    print(missing_df_train.to_string(index=False))
else:
    print("No missing values found in training set!")

print("\n" + "="*50)
print("MISSING VALUES - TEST SET")
print("="*50)
missing_test = df_b.isnull().sum()
missing_test_pct = (df_b.isnull().sum() / len(df_b)) * 100

missing_df_test = pd.DataFrame({
    'Column': missing_test.index,
    'Missing Count': missing_test.values,
    'Missing Percentage': missing_test_pct.values
})

missing_df_test = missing_df_test[missing_df_test['Missing Count'] > 0].sort_values('Missing Count', ascending=False)

if len(missing_df_test) > 0:
    print(missing_df_test.to_string(index=False))
else:
    print("No missing values found in test set!")

==================================================
MISSING VALUES - TRAINING SET
==================================================
Column  Missing Count  Missing Percentage
    E7           6969           77.022546
   V10           6049           66.854553
    S3           5733           63.362069
    M1           5547           61.306366
   M13           5540           61.229001
   M14           5540           61.229001
    M6           5043           55.736074
    V9           4539           50.165782
   S12           3537           39.091512
    M5           3283           36.284262
    M2           3217           35.554819
    S8           3009           33.255968
    M3           2018           22.303271
    E1           1784           19.717065
    P6           1638           18.103448
    P7           1616           17.860301
   E20           1616           17.860301
    P5           1574           17.396110
    V5           1512           16.710875
    V7           1511           16.699823
   V13           1511           16.699823
    S5           1511           16.699823
    E9           1006           11.118479
    I1           1006           11.118479
    E6           1006           11.118479
    E4           1006           11.118479
    E5           1006           11.118479
    E3           1006           11.118479
    E2           1006           11.118479
   E15           1006           11.118479
   E19           1006           11.118479
   E18           1006           11.118479
   E17           1006           11.118479
   E14           1006           11.118479
   E16           1006           11.118479
   E12           1006           11.118479
   E13           1006           11.118479
   E11           1006           11.118479
   E10           1006           11.118479
    E8           1006           11.118479
   M12           1006           11.118479
   M16           1006           11.118479
   M15           1006           11.118479
   M11           1006           11.118479
    I2           1006           11.118479
    I9           1006           11.118479
    I8           1006           11.118479
    I7           1006           11.118479
   M10           1006           11.118479
    I6           1006           11.118479
    I3           1006           11.118479
    I4           1006           11.118479
    I5           1006           11.118479
    P2           1006           11.118479
   P13           1006           11.118479
   P12           1006           11.118479
   P11           1006           11.118479
   P10           1006           11.118479
    P1           1006           11.118479
    M9           1006           11.118479
    M8           1006           11.118479
    M7           1006           11.118479
    M4           1006           11.118479
   M18           1006           11.118479
   M17           1006           11.118479
    S1           1006           11.118479
    P9           1006           11.118479
    P3           1006           11.118479
    P4           1006           11.118479
    S6           1006           11.118479
    S4           1006           11.118479
   S11           1006           11.118479
    S2           1006           11.118479
   S10           1006           11.118479
    P8           1006           11.118479
    V1           1006           11.118479
    S7           1006           11.118479
   V12           1006           11.118479
   V11           1006           11.118479
    S9           1006           11.118479
    V2           1006           11.118479
    V4           1006           11.118479
    V3           1006           11.118479
    V6           1006           11.118479
    V8           1006           11.118479

==================================================
MISSING VALUES - TEST SET
==================================================
No missing values found in test set!